spring:
  datasource:
    url: jdbc:h2:mem:springleTest
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
